### ISSUE TITLE
有什么办法改进吗

### ISSUE THREAD

**Issue by luckypoem** [felix021/mixo#1]
试用了一下你这个程序，发现打开youtube很慢。有什么办法改进吗

**Comment by luckypoem** [comment]
哦，服务器和客户机器2边都运行一下make,从而生成xor.so文件，然后在客户机器上，用chrome+switchyproxy,这样在chrome里面终于能打开youtube.com了

**Comment by felix021** [comment]
不好意思现在才看到，不过还好你自己已经解决了，赞
